### ISSUE TITLE
Bug: Universal Terminal Hotkey Opens To Extended Pattern Access Terminal Instead Of Crafting Terminal

### ISSUE THREAD

**Issue by amenbr1** [Mari023/AE2WirelessTerminalLibrary#271] opened 2024-05-26 06:24 UTC
Steps to reproduce:

1. Craft Universal Terminal with:
Wireless Crafting Terminal,
Wireless Encoding Terminal,
Extended Access Terminals (ExtendedAE),
(optionally the regular Access Terminal)

2. Open the Universal Terminal with the "Open Wireless Terminal" AE2 hotkey

Expected:
Universal Terminal opens on the Wireless Crafting Terminal menu.

Actual:
Universal Terminal opens on the Extended Access Terminal

**Comment by Mari023** [comment] 2024-05-26 11:30
duplicate of #253
this should be fixed in the latest ExtendedAE version

**Closed by Mari023** 2024-05-26 11:30 UTC
