### ISSUE TITLE
No usage instructions

### ISSUE THREAD

**Issue by pixartist** [Mari023/AE2WirelessTerminalLibrary#308] opened 2024-10-21 13:16 UTC
It is absolutely unclear how to use this mod. There is absolutely no information available on how to link these devices and to what.

**Comment by Mari023** [comment] 2024-10-21 14:11
duplicate of #189
I am do not enjoy writing larger amounts of text, and thus I have always postponed writing documentation, tho I am aware that there should be some.

**Closed by Mari023** 2024-10-21 14:11 UTC
