### ISSUE TITLE
[1.19.2, 1.20.1] Crash without crash report

### ISSUE THREAD

**Issue by aking4125** [Mari023/AE2WirelessTerminalLibrary#163] opened 2022-10-04 21:34 UTC
Hello,

Upon adding this mod to my pack, the game crashes but no crashlog is generated. Here is the log file: 
[debug.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/9711028/debug.log)

Removing this mod allows the game to load correctly.

**Comment by Flame1211** [comment] 2022-12-08 09:14
+1

**Comment by IamRyan30** [comment] 2022-12-23 01:27
Same issue here. [Here](https://gist.github.com/IamRyan30/872eeb23186a8a4497d2373a33994f74#file-1-19_wireless_terminal_crash-log-L318)'s another log with the same problem.

**Comment by Haifischkeks** [comment] 2023-01-03 23:33
Greetings, same problem. 

Crash instantly with ext code: 1 when enabling the mod. 

Forge: 43.2.3 
Mod: 12.8.4

No Crashfile is created only the latest.log can be provided.
[latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/10340311/latest.log)

disabling lets the modpack start normally.
Making a modpack just with AE2 and this addition seems to let it start, so it might be another mod. 
Might be going 1 by 1 and see which one it is but that will take time.  (since i can't really read the latest.log and see what causes it..)

**Comment by BobminiJr** [comment] 2023-01-05 17:15
was there ever a solution to this problem? cuz i just wanna play with the mod :(

**Comment by Mari023** [comment] 2023-01-05 20:08
I haven't been able to reproduce this bug, that makes it very hard for me to fix.
the only thing I know (from the log) is that somehow a mixin fails to apply

the only reason I could think of is some other mod is removing the 
`net.minecraft.world.item.ItemStack#useOn` method or changing the signature of it.

**Comment by Haifischkeks** [comment] 2023-01-05 20:19
I am going one by one disabling/enabling mods. I try to let you know which one it might be doing it.

**Comment by Xplodin** [comment] 2023-01-12 05:00
I got a crash with ae2 wireless terminals and refined storage's creative crafter mod

**Comment by Mari023** [comment] 2023-01-17 13:42
I just realized all logs here have Not Enough Crashes installed, which is known to sometimes break things, or obscure crashes.
can someone try removing it and post the log here please?

**Comment by IamRyan30** [comment] 2023-01-17 18:14
https://gist.github.com/IamRyan30/400c174251f337faa25339eabebae054

**Comment by Mari023** [comment] 2023-01-18 13:40
so it isn't Not enough crashes for once...
I don't really have any ideas what could cause this

**Comment by Ninezel** [comment] 2023-03-07 17:38
I might have found out why its been crashing, I'll update you guys about the Mixin stuff that get's reconfigured

**Comment by ErdbeerbaerLP** [comment] 2023-03-26 17:41
Also adding my log file to this, maybe it helps somehow. I had it working earlier with most mods, then I added some mods after which it crashed, but now even after disabling thoose added mods it still crashes.

[2023-03-26-7.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/11072464/2023-03-26-7.log)

**Comment by Mari023** [comment] 2023-04-12 23:54
I added a workaround in 12.8.6 which should be released soon
in theory this should fix this issue.
If it still persists, please post a latest.log here

**Comment by Mari023** [comment] 2023-04-16 15:34
the workaround did not help, the same crash is still happening (with another mixin)

**Comment by MrPurple6411** [comment] 2023-04-26 00:28
OK so I have been having this issue after I tried to add a bunch of mods to an ATM8 pack instance.

In the end it was fixed when I removed one mod that I had added......

The odd thing is when I made a fresh clean instance and ONLY installed the things required for that mod as well as this one they loaded up just fine.

So I think it has to be some form of 3 way interaction and the bigger issue is that I don't see that mod in the logs of the other people above having this issue.


That being said I have been able to replicate the issue reliably by downloading a fresh [ATM8](https://www.curseforge.com/minecraft/modpacks/all-the-mods-8) 1.0.17 pack and then installing [Create: The Factory Must Grow](https://www.curseforge.com/minecraft/mc-mods/create-industry)


[debug.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/11327774/debug.log)

That being said it seems to be a slightly different mixin:

[25Apr2023 18:23:38.958] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed ae2wtlib.mixins.json:PlayerInventoryInsertStack -> net.minecraft.world.entity.player.Inventory: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on insertStackInME could not find any targets matching 'add(Lnet/minecraft/world/item/ItemStack;)Z' in net.minecraft.world.entity.player.Inventory. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> ae2wtlib.mixins.json:PlayerInventoryInsertStack -> Prepare Injections ->  -> handler$cno000$insertStackInME(Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]

**Comment by Delfite** [comment] 2023-05-06 02:45
https://github.com/DrMango14/Create__The_Factory_Must_Grow/issues/2

**Comment by FearAK** [comment] 2023-05-07 07:37
Still no fix to this? :( I really wanna use ae2 but without this mod I have to use refined storage

**Comment by Rainee4563** [comment] 2023-06-09 23:45
seems like the crash I am having is related to this so I thought I would upload my log and hope it helps
https://mclo.gs/mvQ2ek5

**Comment by Ve6om** [comment] 2023-07-16 23:33
@Mari023 Referring to #210, we could possibly work around using a mixins for the inventory. I have Discord and would be willing to help resolve this ASAP.

**Comment by Mari023** [comment] 2023-07-16 23:40
> @Mari023 Referring to #210, we could possibly work around using a mixins for the inventory. I have Discord and would be willing to help resolve this ASAP.

we can try, tho I tried fixing it once by converting one mixin to use an event, and it just failed on a different mixin

I joined your discord

**Comment by Mari023** [comment] 2023-07-17 18:08
should be finally fixed in 1.19.2 and 1.20.1

**Closed by Mari023** 2023-07-17 18:08 UTC
Labels: bug

**Comment by Mari023** [comment] 2023-07-20 18:49
I found the root cause: the mixin refmap is called `mixin.refmap.json`
some other mod had a mixin refmap with the same name, which meant mine was overridden

**Comment by Xplodin** [comment] 2023-07-23 15:03
gotta crash with:
Mixin apply failed AEInfinityBooster.mixins.json:MixinWirelessTerminalMenuHost -> appeng.helpers.WirelessTerminalMenuHost: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on testWap could not find any targets matching 'testWap' in appeng.helpers.WirelessTerminalMenuHost. Using refmap AEInfinityBooster.refmap.json [PREINJECT Applicator Phase -> AEInfinityBooster.mixins.json:MixinWirelessTerminalMenuHost -> Prepare Injections ->  -> handler$zle000$testWap(Lappeng/api/implementations/blockentities/IWirelessAccessPoint;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on testWap could not find any targets matching 'testWap' in appeng.helpers.WirelessTerminalMenuHost. Using refmap AEInfinityBooster.refmap.json [PREINJECT Applicator Phase -> AEInfinityBooster.mixins.json:MixinWirelessTerminalMenuHost -> Prepare Injections ->  -> handler$zle000$testWap(Lappeng/api/implementations/blockentities/IWirelessAccessPoint;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor28.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at appeng.core.definitions.AEItems.lambda$static$16(AEItems.java:139) ~[appliedenergistics2-forge-15.0.5-beta.jar%23643!/:15.0.5-beta]
	at appeng.core.definitions.AEItems.item(AEItems.java:313) ~[appliedenergistics2-forge-15.0.5-beta.jar%23643!/:15.0.5-beta]
	at appeng.core.definitions.AEItems.item(AEItems.java:304) ~[appliedenergistics2-forge-15.0.5-beta.jar%23643!/:15.0.5-beta]
	at appeng.core.definitions.AEItems.<clinit>(AEItems.java:139) ~[appliedenergistics2-forge-15.0.5-beta.jar%23643!/:15.0.5-beta]
	at appeng.core.AppEngBootstrap.runEarlyStartup(AppEngBootstrap.java:72) ~[appliedenergistics2-forge-15.0.5-beta.jar%23643!/:15.0.5-beta]
	at net.minecraft.server.Bootstrap.handler$bgl000$initRegistries(Bootstrap.java:2041) ~[client-1.20.1-20230612.114412-srg.jar%231082!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:57) ~[client-1.20.1-20230612.114412-srg.jar%231082!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%231082!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]



1.20.1

**Comment by Mari023** [comment] 2023-07-23 15:22
@Xplodin that is an issue with [AEInfinityBooster](https://github.com/Hexeption/AEInfinityBooster) (probably this one: https://github.com/Hexeption/AEInfinityBooster/issues/11)

it is unrelated to ae2wtlib.

**Comment by Xplodin** [comment] 2023-07-23 15:46
> @Xplodin that is an issue with [AEInfinityBooster](https://github.com/Hexeption/AEInfinityBooster) (probably this one: [Hexeption/AEInfinityBooster#11](https://github.com/Hexeption/AEInfinityBooster/issues/11))
> 
> it is unrelated to ae2wtlib.
ah crap my bad.
Sorry.
