### ISSUE TITLE
1.19.2 Crash on Mixin at load time FTB Skies

### ISSUE THREAD

**Issue by Saereth** [Mari023/AE2WirelessTerminalLibrary#209] opened 2023-07-04 18:26 UTC
Hi, I'm getting a mixin crash when the mod tries to load currently in mc 1.19.2 Forge.

MC 1.19.2
Forge: 43.2.14
AE2 version: appliedenergistics2-forge-12.9.5.jar
AE2WTlib Version: 12.9.5.jar

Here is the latest.log showing the error
https://gist.github.com/Saereth/1205f881254a8639f36002a14f6d43c6

Relevant section:
`[04Jul2023 11:22:09.505] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed ae2wtlib.mixins.json:PlayerInventoryInsertStack -> net.minecraft.world.entity.player.Inventory: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on insertStackInME could not find any targets matching 'add(Lnet/minecraft/world/item/ItemStack;)Z' in net.minecraft.world.entity.player.Inventory. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> ae2wtlib.mixins.json:PlayerInventoryInsertStack -> Prepare Injections ->  -> handler$cko000$insertStackInME(Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]`

If I can provide any more information I'd be happy to help, thanks for looking into this!

**Comment by Mari023** [comment] 2023-07-04 20:21
Duplicate of #163 
I don't really know why this happens, it works with just ae2wtlib + dependencies
it is also seems to be exclusive to 1.19.2

**Closed by Mari023** 2023-07-04 20:21 UTC
