### ISSUE TITLE
1.20.1 Items disappearing with in trinket slot

### ISSUE THREAD

**Issue by Gamerbolts** [Mari023/AE2WirelessTerminalLibrary#242] opened 2024-02-11 19:52 UTC
Hello!

I am using my own modpack here https://www.curseforge.com/minecraft/modpacks/pxc-fabric-adventure

Noticed that when the wireless terminal is equipped into the head slot for trinkets that when opening it and putting items into the crafting grid then closing the terminal if you reopen it then the items are gone, no longer in the ME system just vanished. If you put the wireless terminal into the hotbar and right click then put items into the grid you can close and reopen and it works. Then you put the grid back into your head slot and open and try a crafting recipe, close, reopen and the items are there again from when it was on the hotbar. So it is essentially deleting the items and I am not sure what to do. I have no idea if this is due to this mod, AE2 or Trinkets. Hopefully it can be resolved. Thanks!

**Comment by Gamerbolts** [comment] 2024-02-20 01:22
Interesting, well I hope you can fix it if you can, if not is there way to prevent the wireless terminal from going into the trinket slot? I am created a modpack for others to play and would not like them to lose items.

**Comment by Mari023** [comment] 2024-02-20 09:57
> is there way to prevent the wireless terminal from going into the trinket slot?

you can remove the items from the trinkets tags using a datapack or kubejs

**Comment by Gamerbolts** [comment] 2024-02-20 12:09
Thank you, i'll do this

**Comment by Mari023** [comment] 2024-03-06 15:44
since the fix for this bug would be rather complicated, and only applies to 1.20.1, I won't be fixing this

**Closed by Mari023** 2024-03-06 15:44 UTC
Labels: bug, wontfix

**Comment by lexi-the-cute** [comment] 2024-07-23 06:10
i presume this is the code that loses the reference to the ItemStack when in a trinket slot? https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/53cc53c68e97ae0da51dd65110a4e7a8a2996645/src/main/java/de/mari_023/ae2wtlib/terminal/ItemWT.java#L154-L159

**Comment by Mari023** [comment] 2024-07-23 07:41
> i presume this is the code that loses the reference to the ItemStack when in a trinket slot?
> 
> https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/53cc53c68e97ae0da51dd65110a4e7a8a2996645/src/main/java/de/mari_023/ae2wtlib/terminal/ItemWT.java#L154-L159

no, that is just responsible to load data from an already present ItemStack

the issue is that the ItemStack instance in the slot changes, but WTMenuHost doesn't know about this, so WTMenuHost#getItemStack still returns the old instance, where all changes are then saved to (but lost, since that stack isn't stored anywhere else)

AE2 has a workaround for that, but it only works for the player inventory, but not trinkets. (see WirelessTerminalMenuHost#ensureItemStillInSlot)
(in later minecraft versions this is fixed by just always directly getting the ItemStack from the slot, but in 1.20.1, we don't even *know* the slot if it is a trinkets slot)

**Comment by lexi-the-cute** [comment] 2024-07-23 23:55
> > i presume this is the code that loses the reference to the ItemStack when in a trinket slot?
> > https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/53cc53c68e97ae0da51dd65110a4e7a8a2996645/src/main/java/de/mari_023/ae2wtlib/terminal/ItemWT.java#L154-L159
> 
> no, that is just responsible to load data from an already present ItemStack
> 
> the issue is that the ItemStack instance in the slot changes, but WTMenuHost doesn't know about this, so WTMenuHost#getItemStack still returns the old instance, where all changes are then saved to (but lost, since that stack isn't stored anywhere else)
> 
> AE2 has a workaround for that, but it only works for the player inventory, but not trinkets. (see WirelessTerminalMenuHost#ensureItemStillInSlot) (in later minecraft versions this is fixed by just always directly getting the ItemStack from the slot, but in 1.20.1, we don't even _know_ the slot if it is a trinkets slot)

I wonder if we can assign each terminal a unique id in the nbt and scan all the non-inventory slots for it when attempting to save the data. Are we able to see the data if we check slots sequentially?

**Comment by AlienXtream** [comment] 2024-10-25 17:32
i know this is an older issue and one that isn't getting a fix in 1.20.1 but i found a workaround. setting the terminal to "clear inventory after close" prevents items in the crafting slots getting deleted and applying any upgrades outside the trinket slot then returning it to the trinket slot does circumvent the issue. mentioning this in case anyone else comes across this when looking up the issue and needs a solution/workaround.
