### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by Ninezel** [Mari023/AE2WirelessTerminalLibrary#190] opened 2023-03-07 17:08 UTC
Trying to find out what is crashing the mod. Fatal Crash at the bottom of the gist.
https://gist.github.com/Ninezel/296fc6dd9503e6dc9af7184c551a4abf

**Comment by Ninezel** [comment] 2023-03-07 17:09
More info, running 1.19.2 on Forge 43.2.6

**Comment by Mari023** [comment] 2023-03-07 17:15
duplicate of #163

**Closed by Mari023** 2023-03-07 17:15 UTC
