### ISSUE TITLE
Incompatibility with "Create: The Factory Must Grow"

### ISSUE THREAD

**Issue by Delfite** [Mari023/AE2WirelessTerminalLibrary#201] opened 2023-05-06 11:28 UTC
All info related to the crash has been documented [here.](https://github.com/DrMango14/Create__The_Factory_Must_Grow/issues/2)

Note: This crash happens regardless of the version of AE2 Wireless Terminals installed in the pack but will not occur if `Create: The Factory Must Grow` is downgraded to `createindustry-0.3.0-1.19.2.jar`

**Comment by Mari023** [comment] 2023-05-07 12:00
I don't think Create: The Factory Must Grow directly causes this, as this exact same issue can also happen without it

either way, this is a duplicate of #163

**Closed by Mari023** 2023-05-07 12:00 UTC
