### ISSUE TITLE
Incompatible with latest AE2 version

### ISSUE THREAD

**Issue by griffin4cats** [Mari023/AE2WirelessTerminalLibrary#74] opened 2021-08-01 07:11 UTC
Latest is 8.4.0 but it requires 8.3.0

**Comment by Mari023** [comment] 2021-08-01 11:37
duplicate of #69 
there is an alpha version that works with ae2 8.4, however due to an ae2 bug (#73) that makes it impossible to test some parts of my mod, I can't make a proper release (nor recomend using it)

**Closed by Mari023** 2021-08-01 11:37 UTC
