### ISSUE TITLE
[1.20.4] Clientside crash when trying to open wireless terminals

### ISSUE THREAD

**Issue by thinkuverymuch** [Mari023/AE2WirelessTerminalLibrary#250] opened 2024-03-18 09:36 UTC
neoforge-20.4.200
ae2wtlib-17.6.3-beta

When trying to open any of the wireless terminals from this mod, I get kicked out of the server with an error message.

**Wireless Crafting Terminal**
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.world.inventory.MenuType@2b455357' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]`

**Wireless Pattern Access Terminal**
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.world.inventory.MenuType@35ed8c4d' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]`

**Wireless Pattern Encoding Terminal**
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.world.inventory.MenuType@5ad647a6' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Stable)]`

**Comment by Mari023** [comment] 2024-03-18 14:28
I was worried something like this would happen.
I think I have a fix for this in the next version, however I can't reproduce this, so I can't test if the fix actually helps.
if this is still happens with the new version, please reopen the issue

**Closed by Mari023** 2024-03-18 14:28 UTC
