### ISSUE TITLE
changing Magnet Mode via GUI doesn't work on forge 1.18.2

### ISSUE THREAD

**Issue by FearAK** [Mari023/AE2WirelessTerminalLibrary#167] opened 2022-10-14 12:54 UTC
Latest version of this mod and ae2 and forge.
Wether I use the option to get it in inventory or me system it always goes to inventory and im not using any other magnets.

**Comment by Mari023** [comment] 2022-10-14 13:35
I cannot reproduce it.
a) which minecraft version are you using (1.19.2 or 1.18.2)
b) do you have the filter set (pickup and insert to me have independent filters)
c) can you insert the item manually?

potential problems may be:
- the terminal can't connect to the system (system too far away, or not loaded)
- the item can't be inserted (i.e. if the system is full)

**Comment by StarskyXIII** [comment] 2022-11-04 02:31
It seems gui button would not actually change Magnet mode. 
And Magnet Card doesn't work with AE2 build-in terminal on Forge side0
Magnet Mode only changed with hotkey.

**Comment by Mari023** [comment] 2022-11-04 12:27
> And Magnet Card doesn't work with AE2 build-in terminal on Forge side.

which one? It doesn't work with the normal wireless terminal, only with the wireless crafting terminal

> It seems gui button would not actually change Magnet mode.

I can reproduce this on 1.18.2 now

**Comment by StarskyXIII** [comment] 2022-11-04 14:29
>which one? It doesn't work with the normal wireless terminal, only with the wireless crafting terminal

Oh okay, now I get it!

**Comment by Mari023** [comment] 2022-11-04 14:58
the fix for this would be rather complicated, and since this only happens on forge 1.18.2 (which is near the end of support anyway), I won't fix this.

as a workaround, use the hotkey instead.

**Closed by Mari023** 2022-11-04 14:58 UTC
Labels: wontfix
